/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(css_decode_symbols.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d0fd2773c2af404c673b5b0a6e317e07)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cssmods/css_decode_symbols.h>
// pydoc.h is automatically generated in the build directory
#include <css_decode_symbols_pydoc.h>

void bind_css_decode_symbols(py::module& m)
{

    using css_decode_symbols = ::gr::cssmods::css_decode_symbols;


    py::class_<css_decode_symbols,
               gr::block,
               gr::basic_block,
               std::shared_ptr<css_decode_symbols>>(
        m, "css_decode_symbols", D(css_decode_symbols))

        .def(py::init(&css_decode_symbols::make),
             py::arg("sf"),
             py::arg("bw"),
             py::arg("zero_padding_ratio"),
             D(css_decode_symbols, make))


        ;
}
