/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(css_demodulate_symbols.h) */
/* BINDTOOL_HEADER_FILE_HASH(aea7d373f9549b3d55c90e0f5c56445b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cssmods/css_demodulate_symbols.h>
// pydoc.h is automatically generated in the build directory
#include <css_demodulate_symbols_pydoc.h>

void bind_css_demodulate_symbols(py::module& m)
{

    using css_demodulate_symbols = ::gr::cssmods::css_demodulate_symbols;


    py::class_<css_demodulate_symbols,
               gr::block,
               gr::basic_block,
               std::shared_ptr<css_demodulate_symbols>>(
        m, "css_demodulate_symbols", D(css_demodulate_symbols))

        .def(py::init(&css_demodulate_symbols::make),
             py::arg("sf"),
             py::arg("bw"),
             py::arg("zero_padding_ratio"),
             D(css_demodulate_symbols, make))


        ;
}
