/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(css_modulate.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9382eb307be4da1f1d117012ebe1fdb3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cssmods/css_modulate.h>
// pydoc.h is automatically generated in the build directory
#include <css_modulate_pydoc.h>

void bind_css_modulate(py::module& m)
{

    using css_modulate    = gr::cssmods::css_modulate;


    py::class_<css_modulate, gr::block, gr::basic_block,
        std::shared_ptr<css_modulate>>(m, "css_modulate", D(css_modulate))

        .def(py::init(&css_modulate::make),
           D(css_modulate,make)
        )
        



        ;




}








