/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(css_symbols_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(57271a544dfa6db9069fe936cf249ebc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cssmods/css_symbols_decode.h>
// pydoc.h is automatically generated in the build directory
#include <css_symbols_decode_pydoc.h>

void bind_css_symbols_decode(py::module& m)
{

    using css_symbols_decode    = gr::cssmods::css_symbols_decode;


    py::class_<css_symbols_decode, gr::block, gr::basic_block,
        std::shared_ptr<css_symbols_decode>>(m, "css_symbols_decode", D(css_symbols_decode))

        .def(py::init(&css_symbols_decode::make),
           D(css_symbols_decode,make)
        )
        



        ;




}








