/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(css_frame_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(82a7fe2e15e467026326351d2050e91b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cssmods/css_frame_sync.h>
// pydoc.h is automatically generated in the build directory
#include <css_frame_sync_pydoc.h>

void bind_css_frame_sync(py::module& m)
{

    using css_frame_sync = ::gr::cssmods::css_frame_sync;


    py::class_<css_frame_sync,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<css_frame_sync>>(m, "css_frame_sync", D(css_frame_sync))

        .def(py::init(&css_frame_sync::make),
             py::arg("sf"),
             py::arg("bw"),
             py::arg("zero_padding_ratio"),
             D(css_frame_sync, make))


        ;
}
